#!/usr/bin/bash
# Release holds in a subtree
# $1    Dataset at the top of the subtree
# $2    Hold tag to release. If not specified, all holds will be released.

source ~/bashinit
source $mydir/rootcheck
source $mydir/zfsbuildfsarray
source $mydir/zfsdelallholds
bashinit
rootcheck

if [[ $1 = '' ]]; then 
    log_msg 'FATAL: A dataset must be provided as $1.'
    exit 8
else
    sourcefs=$1
fi
if [[ $2 != '' ]]; then tag=$2; else unset tag; fi

if [[ $autoproceed = '' ]]; then autoproceed='N'; fi
if [[ $depth = '' ]]; then unset depth; fi   # Depth of subtree. E.g., '1'
if [[ $includes = '' ]]; then includes=(); fi
buildfsarraytype='snapshot'     # Build an array of snapshots (ZFS dataset type)

buildfsarray $sourcefs

if [[ ${#fsarray[@]} -gt 0 ]]; then
    if [[ $autoproceed != 'Y' ]]; then
        if [[ $tag = '' ]]; then msgtag='all'; else msgtag=$tag; fi
        log_msg "INFO: Will release $msgtag holds on these snapshots:"
        for snap in ${fsarray[@]}; do
            echo $snap $tag
        done
        read -p 'Press enter to continue.'
    fi
    for snap in ${fsarray[@]}; do
        delallholds $snap $tag
    done
fi

