"""Backup configuration compatibility shim.

Re-exports the public API from logging_config, config_core, and feature_config
so existing callers can be migrated incrementally.
"""

from logging_config import (
    log_msg,
    set_log_sink,
    get_log_sink,
    MSG_LEVELS,
    DEFAULT_MSG_LEVEL,
    get_msg_level,
)

from config_core import (
    CONFIG_PATH,
    CONFIG_VERSION,
    _deep_copy,
    get_profiles_dir,
    BACKUP_DEFAULTS,
    DASHBOARD_DEFAULTS,
    load_config,
    save_config,
    save_msg_level,
    get_docs_editor,
    save_docs_editor,
    UI_STATE_DEFAULTS,
    get_ui_state,
    save_ui_state,
    DEFAULT_LOG_RETENTION_DAYS,
    DEFAULT_HISTORY_RETENTION_DAYS,
    SESSION_LOG_DIR,
    get_log_retention_days,
    save_log_retention_days,
    get_history_retention_days,
    save_history_retention_days,
    prune_old_logs,
    get_dashboard_config,
    save_dashboard_config,
)

from feature_config import (
    get_backup_config,
    save_backup_config,
    OFFSITE_DEFAULTS,
    get_offsite_config,
    save_offsite_config,
    RESTORE_DEFAULTS,
    get_restore_config,
    save_restore_config,
    get_pools,
    get_pool_names,
    get_offsite_candidate_names,
    save_pools,
    get_checkagainst,
    save_checkagainst,
    get_archive_path,
    save_archive_path,
    get_prune_label,
    save_prune_label,
    get_prune_pools_order,
    save_prune_pools_order,
    DEFAULT_RETENTION,
    get_all_retention,
    get_retention,
    save_retention,
    import_legacy_retention,
    SCRUB_MANAGER_DEFAULTS,
    SCRUB_STATE_PATH,
    get_scrub_manager_config,
    save_scrub_manager_config,
    load_scrub_state,
    save_scrub_state,
    SNAPFILE,
    OFFSITE_SNAPFILE,
    _read_snapfile,
    _write_snapfile,
    _remove_snapfile,
    save_snapshot_name,
    remove_snapfile,
    _build_snapshot_name,
    generate_snapshot_name,
    save_offsite_snapshot_name,
    generate_offsite_snapshot_name,
)
